version: "3"
services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb+srv://banerjeesayan554_db_user:Kndw3rofBV4CBcIi@cluster0.l1snj1w.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    volumes:
      - ./backend:/app   # Mount local code into container

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
